language: c
sudo: false
os: linux
cache: ccache

addons:
  apt:
    sources:
       - ubuntu-toolchain-r-test
    packages:
       - libnuma-dev
       - bison

before_script:
  - ulimit -c unlimited
  - make -f run_configure.mk SPEC=linux_x86-64 OMRGLUE=./example/glue
  - export GTEST_FILTER=-*dump_test_create_dump_*

script: make && make test

